repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
          exclude: ^(virtualenv|venv)/

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: 'v2.0.4'
      hooks:
        - id: autopep8
          exclude: ^(virtualenv|venv)/

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.21.3
      hooks:
        - id: commitizen
          stages: [commit-msg]
