[tool.commitizen]
name = "cz_conventional_commits"
changelog_file = "CHANGELOG.md"
changelog_incremental = true
tag_format = "$version"
version_scheme = "semver"
version = "0.2.0"
update_changelog_on_bump = true
major_version_zero = true
